name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Debug Secrets
        run: |
          echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_S3_ACCESSKEYID }}"
          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_S3_SECRETACCESSKEY }}"
          echo "AWS_REGION=${{ secrets.AWS_EC2_REGION }}"

      - name: Set up Node.js for server
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install dependencies for server
        run: |
          cd server
          npm install

      - name: Set up Node.js for client
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install dependencies for client
        run: |
          cd client
          npm install

      - name: Build client
        run: |
          cd client
          npm run build

      - name: List client/dist files
        run: |
          ls -la client/dist
   

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_S3_ACCESSKEYID }}
          aws-secret-access-key: ${{ secrets.AWS_S3_SECRETACCESSKEY }}
          aws-region: ${{ secrets.AWS_EC2_REGION }}

      - name: Upload to S3
        run: |
          aws s3 sync client/dist s3://bucket0703 --delete &&
          aws cloudfront create-invalidation --distribution-id EKRBCNRYC71U8 --paths "/*"
      - name: List files in server directory
        run: |
          ls -la server
      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./server
          push: true
          tags: yajie0219/test:latest

      - name: Log in to Docker Hub
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Push Docker image to Docker Hub
        run: docker push yajie0219/test

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Pull Docker image from Docker Hub
        run: docker pull yajie0219/test

      - name: Clean up unused Docker resources
        run: docker system prune -af

      - name: Deploy Docker container to EC2
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USER: ${{ secrets.EC2_USER }}
        run: |
          echo "Creating SSH key file"
          echo "$SSH_PRIVATE_KEY" > aaa.pem
          chmod 600 aaa.pem
          echo "Connecting to EC2 and deploying Docker container"
          ssh -o StrictHostKeyChecking=no -i aaa.pem $EC2_USER@$EC2_HOST '
            echo "Pulling Docker image"
            docker pull yajie0219/test &&
            echo "Stopping existing container if any"
            docker stop app || true &&
            echo "Removing existing container if any"
            docker rm app || true &&
            echo "Running new Docker container"
            docker run -d --name app -p 3000:3000 --env-file /home/ubuntu/climbbook/.env yajie0219/test'